-- Q-1
SELECT * FROM DEPOSIT;
-- Q-2
SELECT * FROM BORROW;	
-- Q-3
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT;
-- Q-4
SELECT LOANNO,AMOUNT FROM BORROW;
-- Q-5
SELECT * FROM BORROW
WHERE BNAME = 'ANDHERI';
-- Q-6
SELECT ACTNO,AMOUNT FROM DEPOSIT
WHERE ACTNO = 106;
-- Q-7
SELECT CNAME FROM BORROW
WHERE AMOUNT > 5000;
-- Q-8
SELECT CNAME FROM DEPOSIT
WHERE ADATE > '1995-12-1';
-- Q-9
SELECT CNAME FROM DEPOSIT
WHERE ACTNO < 105;
-- Q-10
SELECT CNAME FROM CUSTOMERS
WHERE CITY = 'NAGPUR'OR CITY = 'DELHI';
--Q-11
SELECT CNAME,BNAME FROM DEPOSIT
WHERE AMOUNT > 400 AND ACTNO < 105;
--Q-12
SELECT * FROM BORROW
WHERE AMOUNT >= 3000 AND AMOUNT <= 8000;
--Q-13
SELECT * FROM DEPOSIT
WHERE BNAME != 'ANDHERI';
--Q-14
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
WHERE BNAME = 'AJNI' OR
BNAME = 'KAROLBAGH' OR
BNAME = 'M.G.ROAD' AND
ACTNO < 104;
--Q-15
SELECT LOANNO,CNAME FROM BORROW
WHERE BNAME NOT IN('VIRAR','AJNI');
--Q-16
SELECT CNAME FROM DEPOSIT
WHERE CNAME NOT IN ('MINU')
--Q-17
SELECT CNAME FROM DEPOSIT
WHERE BNAME IS NULL
--Q-18
SELECT DISTINCT BNAME FROM DEPOSIT
--Q-19
SELECT TOP 50 PERCENT * FROM BORROW
--Q-20
SELECT TOP 5 ACTNO FROM DEPOSIT

--PART - B
--Q-1
SELECT TOP 5 *FROM DEPOSIT

--Q-2
SELECT TOP 3 * FROM DEPOSIT
WHERE AMOUNT>1000

--Q-3
SELECT TOP  5 LOANNO, CNAME FROM BORROW
WHERE BNAME NOT IN ('ANDHERI')

--Q-4
SELECT * FROM DEPOSIT
WHERE ACTNO<105 OR ACTNO > 109

--Q-5
SELECT * FROM BORROW
WHERE (AMOUNT > 1000 AND AMOUNT <=7000) AND (LOANNO > 250 AND LOANNO <600)


--PART-C

--Q-1
SELECT ACTNO, CNAME, BNAME , AMOUNT , ADATE FROM DEPOSIT 
WHERE AMOUNT>5000

--Q-2
SELECT DISTINCT * FROM CUSTOMERS

--Q-3
SELECT * FROM BORROW
WHERE (AMOUNT > 3000) AND (LOANNO%3!=0)

--Q-4
SELECT * FROM DEPOSIT
WHERE (AMOUNT>2000) AND (ACTNO>100 AND ACTNO <105) AND (ADATE > '1995-3-1' AND ADATE < '1996-3-27') 

--Q-5
SELECT * FROM BORROW
WHERE (LOANNO%2 = 0)  --EVEN

SELECT * FROM BORROW
WHERE (LOANNO%2 != 0)  --ODD
